
#eureka:
#  instance:
#    hostname: localhost

server:
  port: 8761
spring:
  application:
    name: Discovery-Server

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

