#mybatis.mapper-locations=classpath:organizationMapper.xml
#mybatis.config-location=classpath:mybatis-config.xml
#
#spring.datasource.url=jdbc:mysql://192.168.21.225:3306/mytest
#spring.datasource.username=testuser
#spring.datasource.password=19811981
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#
#spring.application.name=organizationservice
#spring.profiles.active=default
#
#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.defaultZone = http://192.168.21.120:8761/eureka/

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.84:8761/eureka/

spring:
#  application:
#    name: organization-service
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: orgChangeTopic
#          content-type: application/json
#      kafka:
#        binder:
#          brokers: 127.0.0.1:9092
#          #zk-nodes: 192.168.21.225:2181

logging.level.org.springframework.cloud: DEBUG
logging.level.org.springframework.web: TRACE
logging.level.org.springframework.http: TRACE
#logging.level.web: TRACE
#logging.level.com.netflix: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath:organizationMapper.xml
  config-location: classpath:mybatis-config.xml

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.21.182:8091/user

#logging:
#  file: ${spring.application.name}.log
server:
  port: 8090

grpc:
  server:
    port: 50051
---
spring:
  profiles: dev
  datasource:
    username: root
    password: 19811981
    url: jdbc:mysql://localhost:3306/organizations?useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

