server:
  port: 8989

#spring.datasource.url=jdbc:mysql://192.168.21.225:3306/mytest
#spring.datasource.username=testuser
#spring.datasource.password=19811981
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mybatis.mapper-locations=classpath:licenseMapper.xml
#mybatis.config-location=classpath:mybatis-config.xml

mybatis:
  mapper-locations: classpath:licenseMapper.xml
  config-location: classpath:mybatis-config.xml
  
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://140.143.45.252:8761/eureka/

#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.defaultZone = http://192.168.21.120:8761/eureka/

#spring.zipkin.base-url=http://192.168.21.120:9411
#spring.sleuth.sampler.probability=1.0

spring:
  zipkin:
    base-url: http://127.0.0.1:9411

  sleuth:
    sampler:
      probability: 1.0

  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licesinggroup

      kafka:
        binder:
          brokers: 192.168.21.225:9092
          zk-nodes: 192.168.21.225:2181
#logging.path=logs
logging:
  level:
    org.springframework.cloud.config: DEBUG
#logging.file=${logging.path}/licenseservice.log